replicaCount: 1

image:
  repository: wekee/njwjxy-yaoxue-zhongyaojianbie
  tag: "mcp-server-DrugQA_2.0"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 9000

containerPort: 9000

secret:
  APPSECRET: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

extraEnvVars:
  - name: DEEPSEEK_API_KEY
    value: "xxxxxx"
