replicaCount: 1

image:
  repository: wekee/njwjxy-yaoxue-zhongyaojianbie
  tag: "mcp-server-graphrag_1.0"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8000

containerPort: 8000

secret:
  APPSECRET: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

extraEnvVars:
  - name: GRAPHRAG_API_KEY
    value: "sk-5c96f4b3f885469eb9af52bab183d654"
  - name: GRAPHRAG_ZHIPU_API_KEY
    value: "741770ad1423455f8239d31096d4f43d.YkaiIEdcYi5vPZWi"
