replicaCount: 1

image:
  repository: wekee/njwjxy-yaoxue-zhongyaojianbie
  tag: "backendserver_8.0"
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 5000
  nodePort: 30080

containerPort: 5000

secret:
  APPSECRET: xxxxxxx

extraEnvVars:
  - name: LLM_SERVER_URL
    value: "llm-server.default.svc.cluster.local:8001"
  - name: DEEPSEEK_API_KEY
    value: "xxxxx"
  - name: MEDICINE_URL
    value: "http://mcp-server-graphrag.default.svc.cluster.local:8000/mcp"
  - name: MYSQLURL
    value: "my-mysql.default.svc.cluster.local"
  - name: MYSQLUSER
    value: "root"
  - name: MYSQLPASSWORD
    value: "zhongyao_root"
  - name: MYSQLDATABASE
    value: "zhongyao"
  - name: MYSQLPORT
    value: "3306"
  - name: MYSQLCHARSET
    value: "utf8mb4"
  - name: APPSECRET
    valueFrom:
      secretKeyRef:
        name: appsecret
        key: APPSECRET
