replicaCount: 1

image:
  repository: wekee/njwjxy-yaoxue-zhongyaojianbie
  tag: "tts-server_1.0"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 3000

containerPort: 3000

secret:
  APPSECRET: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

extraEnvVars:
  - name: DASHSCOPE_API_KEY
    value: "xxxxxxxxxxxx"
