apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: backend-server
  namespace: default
spec:
  ingressClassName: nginx
  rules:
    - host: www.njwjxy.cn
      http:
        paths:
          - pathType: Prefix
            backend:
              service:
                name: backend-server
                port:
                  number: 5000
            path: /
          - path: /api/qwen-tts
            pathType: Prefix
            backend:
              service:
                name: tts-server
                port:
                  number: 3000  # 请根据实际服务端口修改
    # This section is only required if TLS is to be enabled for the Ingress
  tls:
    - hosts:
      - www.njwjxy.cn
      secretName: ingress-tls
